### ISSUE TITLE
Generated Blueprint template does not run

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/generator-camel-project#1]
Generated templates for spring and Java DSLs can be run with:
```
> mvn install
> mvn camel:run
```

Unfortunately, the blueprint version does not run successfully. Working on finding a solution.

**Comment by bfitzpat** [comment]
Apparently need to set the config for blueprint as here - https://github.com/jbosstools/jbosstools-fuse/blob/master/editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-blueprint-fuse7/pom.xml#L201

**Comment by lhein** [comment]
check...
https://github.com/jbosstools/jbosstools-fuse/blob/1b75fb082669b47ea08ac07d27e85d6bbe0aff41/editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/util/CamelContextLaunchConfigConstants.java#L31

and

https://github.com/jbosstools/jbosstools-fuse/blob/6110ad55d5fe90ffddf237110f959ea3b6757dca/editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/launching/CamelRunMavenLaunchDelegate.java#L52

There is another command line argument it seems.

**Comment by bfitzpat** [comment]
Thx. I'll give it a shot

**Comment by bfitzpat** [comment]
`$ mvn camel:run -Dcamel.blueprint=true
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building demoblue 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> camel-maven-plugin:2.18.1:run (default-cli) > test-compile @ demoblue >>>
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ demoblue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ demoblue ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ demoblue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\brianf\demoblue\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ demoblue ---
[INFO] No sources to compile
[INFO]
[INFO] <<< camel-maven-plugin:2.18.1:run (default-cli) < test-compile @ demoblue <<<
[INFO]
[INFO]
[INFO] --- camel-maven-plugin:2.18.1:run (default-cli) @ demoblue ---
[INFO] Using org.apache.camel.test.blueprint.Main to initiate a CamelContext
[INFO] Starting Camel ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Aug 22, 2018 12:36:17 PM org.ops4j.pax.swissbox.tinybundles.core.metadata.RawBuilder run
INFO: Copy thread finished.
[ERROR] *************************************
[ERROR] Error occurred while running main from: org.apache.camel.test.blueprint.Main
[ERROR]
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:472)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.RuntimeException: Gave up waiting for BlueprintContainer from bundle "MyBundle"
    at org.apache.camel.test.blueprint.CamelBlueprintHelper.waitForBlueprintContainer (CamelBlueprintHelper.java:363)
    at org.apache.camel.test.blueprint.Main.doStart (Main.java:111)
    at org.apache.camel.support.ServiceSupport.start (ServiceSupport.java:61)
    at org.apache.camel.main.MainSupport.run (MainSupport.java:138)
    at org.apache.camel.main.MainSupport.run (MainSupport.java:390)
    at org.apache.camel.test.blueprint.Main.main (Main.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:472)
    at java.lang.Thread.run (Thread.java:748)
[ERROR] *************************************
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.143 s
[INFO] Finished at: 2018-08-22T12:36:47-06:00
[INFO] Final Memory: 24M/438M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.camel:camel-maven-plugin:2.18.1:run (default-cli) on project demoblue: null: MojoExecutionException: InvocationTargetException: Gave up waiting for BlueprintContainer from bundle "MyBundle" -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

**Comment by bfitzpat** [comment]
Dropped Freeman a note with a simple project to see if he has any ideas.

**Comment by apupier** [comment]
I think it is a known issue for Camel 2.18.1 https://issues.apache.org/jira/browse/CAMEL-10602

**Comment by bfitzpat** [comment]
Issued PR with fixes thanks to Freeman's help https://github.com/camel-tooling/generator-camel-project/pull/25

**Comment by bfitzpat** [comment]
Fixed and closing
