### ISSUE TITLE
combine the camel-project and wsdl2rest generators into one composed generator

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/generator-camel-project#11]
Once the wsdl2rest sub-generator is added, the user can use it by calling "yo camel-project:wsdl2rest", but that will only give them the prompts for the wsdl and the location. We need to dovetail the wsdl2rest generator at the end of the camel-project generator so we have the complete project generation process.

To do this, we will need to migrate the generators/wsdl2rest to use the initializing step of the generator:

initializing() {
    this.composeWith(require.resolve('../app'));
}

In testing, this works pretty well but I will need to figure out how to access options from the main generator inside the sub-generator so I can get the camel DSL type and appropriately put the generated configuration file in the right place.

**Comment by bfitzpat** [comment]
This is now complete with the merging of https://github.com/camel-tooling/generator-camel-project/pull/31.

I am updating the readme (https://github.com/camel-tooling/generator-camel-project/issues/32) and then this should be available to test more easily.

**Comment by bfitzpat** [comment]
@tsedmik This can be considered "done" now if you want to take a crack at testing it? I have updated the readme with some examples of how to use the command-line and --wsdl2rest aspects, and there's a built-in node.js-powered SOAP service (helloservice) that's easy to run (go into the directory and run node manualstart.js to start it (it gives you the URL for the WSDL) and you can use that to generate a Spring- or Blueprint-based wsdl2rest wrapper that runs locally. 

The only issue right now with testing will be the wsdl2rest Blueprint case. It should deploy in a Karaf instance, but it doesn't test standalone (with mvn camel:run) like the standard camel-project case does. There are some open issues (see the bottom of the readme for the two I have currently). 

But this is all committed and deployed up to npm now https://www.npmjs.com/package/generator-camel-project so you should be able to test everything that's working. 

Thanks!

**Comment by tsedmik** [comment]
Hi @bfitzpat, I'm sorry for such a late response. I'm forwarding your request to @djelinek. He's took responsibility for testing Yeoman stuff ;-)

**Comment by djelinek** [comment]
@bfitzpat I have problems with wsdl2rest generated from command line, ouput of wsdl2rest project with prompts and from command line has different output... I used same options in both as describes readme file of generator

With prompts:
```
➜  restapp git:(master) ✗ yo camel-project --wsdl2rest
     _                             _
    / \     _ __     __ _    ___  | |__     ___
   / _ \   | '_ \   / _` |  / __| | '_ \   / _ \
  / ___ \  | |_) | | (_| | | (__  | | | | |  __/
 /_/   \_\ | .__/   \__,_|  \___| |_| |_|  \___|
           |_|
       ____                              _
     /  ___|   __ _   _ __ ___     ___  | |
    |  |      / _` | | '_ ` _ \   / _ \ | |
    |  |___  | (_| | | | | | | | |  __/ | |
     \____|   \__,_| |_| |_| |_|  \___| |_|
 -----------------------------------------------
            Camel Project Generator
                 Version: 0.2.0
 -----------------------------------------------

? Your Camel project name restapp
? Your Camel version 2.22.2
? Camel DSL type (blueprint, spring, spring-boot, or java) spring
? Package name:  com.restapp
? URL to the input WSDL http://localhost:3000/helloworldservice?wsdl
? Name of the output directory for generated artifacts src/main/java
? Address of the generated jaxrs endpoint http://localhost:8081/rest
? Address of the target jaxws endpoint http://localhost:3000/helloworldservice
Creating folders
Copying files
Calling wsdl2rest
   create CXF artifacts for specified WSDL at src/main/java
   create src/main/resources/META-INF/spring/camel-context.xml
   create pom.xml
   create README.md
```

From command line:
```
➜  restapp git:(master) ✗ yo camel-project appname=MyApp camelVersion=2.22.2 camelDSL=spring package=com.myapp wsdl=http://localhost:3000/helloworldservice\?wsdl outdirectory=src/main/java jaxrs=http://localhost:8081/rest jaxws=http://localhost:3000/helloworldservice
Creating folders
Copying files
   create pom.xml
   create README.md
   create src/main/resources/META-INF/spring/camel-context.xml
```

**Comment by bfitzpat** [comment]
Ok I'll take a look. Thanks @tsedmik

**Comment by tsedmik** [comment]
@bfitzpat I assume, that you meant @djelinek :-).Actually, I haven't done anything on generator-camel-project side.

**Comment by bfitzpat** [comment]
> I assume, that you meant @djelinek
I did! Sorry about that! :)

**Comment by djelinek** [comment]
verified
