### ISSUE TITLE
Sanitize default package name provided

### ISSUE THREAD

**Issue by apupier** [camel-tooling/generator-camel-project#13]
in case the foldr in which I create the project contains space or whatever invalid package name, the default proposed is invalid

**Comment by bfitzpat** [comment]
@apupier Do you have any examples of what you tried as invalid? Definitely something to tackle

**Comment by bfitzpat** [comment]
Looks like the generator uses lodash's kebabCase function to do this work. https://lodash.com/docs/4.17.10#kebabCase - Would that work?

**Comment by apupier** [comment]
> Do you have any examples of what you tried as invalid?

I don't remember but I think that i tried '@', '=', '#'

Definition of a package name is here https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-7.4

there are Java methods to check a part of it as mentioned https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-Identifier

In Eclipse, there is org.eclipse.jdt.core.JavaConventions.validatePackageName to check for validate names.

> Looks like the generator uses lodash's kebabCase function to do this work. https://lodash.com/docs/4.17.10#kebabCase - Would that work?

I think the kebabCase will work for spaces but won't replace java specific keywords or '@' for instance.

I don't know Javascript ecosystem enough to give direction where to search for a correct implementation of a "sanitize" java package name in javascript.

**Comment by bfitzpat** [comment]
Created PR - https://github.com/camel-tooling/generator-camel-project/pull/21

**Comment by bfitzpat** [comment]
Merged PR. Closing

**Comment by apupier** [comment]
would worth updating the title as what has been implemented is a validation on the package name but not a "sanitation" of the package name provided by default
