### ISSUE TITLE
Add spring boot template

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/generator-camel-project#18]
We have templates for spring, blueprint, and java -- would be good to add a Spring boot template.

**Comment by bfitzpat** [comment]
This is related to https://issues.jboss.org/browse/FUSETOOLS-3136

**Comment by bfitzpat** [comment]
Looks like there may be something more camel related here - https://mvnrepository.com/artifact/org.apache.camel/camel-spring-boot-dependencies/2.22.1 - but I honestly don't know enough about spring boot dependencies at this point to see whether this may be an equivalent option for the fuse-springboot-bom

**Comment by apupier** [comment]
> Is that what we want here? Or is there a way to do this with a camel bom as well?

I would say that as it is in camel-tooling project, we want to use Camel boms and not Fuse ones.

**Comment by bfitzpat** [comment]
I will take a look at https://github.com/apache/camel/tree/master/examples/camel-example-spring-boot and see if there's a way to massage that for a simpler example like we have with the other templates.

**Comment by bfitzpat** [comment]
Have begun work on this and have the basic case working. You can create a spring-boot Camel project, build it, run it, and see console output from the running timer. I've run into some issues with the --wsdl2rest case (doesn't want to put the generated config in the right location, so working on that next.

**Comment by bfitzpat** [comment]
@tsedmik @djelinek This is now complete and ready for testing when you get around to it. I have a small fix with https://github.com/camel-tooling/generator-camel-project/issues/39 left to commit, but it doesn't impede testing. That fix will just improve the process when these generated projects are imported into the Eclipse-based Fuse Tooling. 

To test, simply use the generator to create a new spring-boot DSL project as you have done with spring and blueprint. :) Let me know if you have any questions!

**Comment by djelinek** [comment]
verified
