### ISSUE TITLE
Provide version for camel-maven-plugin

### ISSUE THREAD

**Issue by apupier** [camel-tooling/generator-camel-project#34]
it will avoid warnings when building the genrated project

```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.wsdl:wsdl:jar:1.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.camel:camel-maven-plugin is missing. @ line 183, column 11
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

**Comment by bfitzpat** [comment]
Will add <version>${camel.version}</version> to the template pom's for spring (it's already included in the blueprint ones)

**Comment by bfitzpat** [comment]
Fixing as part of the https://github.com/camel-tooling/generator-camel-project/pull/31 PR, since the Spring poms changed slightly there already.

**Comment by bfitzpat** [comment]
This will be resolved when https://github.com/camel-tooling/generator-camel-project/pull/31 is merged.

**Comment by bfitzpat** [comment]
Fixed as part of https://github.com/camel-tooling/generator-camel-project/pull/31
